     function xt=burgers_adaptive_pde(t,x)
%...
%... Set global variables
     global eps
     global tc
     global D1
     tc = t;
%...
%... Transfer dependent variables  
     u=x;
%...
%... Spatial derivatives and boundary conditions
%...   
     uz=D1*u;
     uzz=D1*uz;
	 uzzz=D1*uzz;
%...
%... Partial differential equations
%...
     ut=-u.*uz+eps*uzz;
%...
%... Transfer temporal derivatives
%...
     xt=ut;
